preprocess_params:
  model: "huggingface"
  composers: "none"
  tokenizer: "codellama/CodeLlama-34b-hf"

inference_params :
    model: "codellama-34b"
    seq_max_len: 16000
    input_data_path: ""
    context_max: -1

eval_params:
    device: cuda
