preprocess_params:
  model: "huggingface"
  composers: "none"
  tokenizer: "bigcode/starcoderbase-7b"

inference_params :
    model: "starcoderbase-7b"
    seq_max_len: 8000
    input_data_path: ""
    context_max: -1

eval_params:
    device: cuda
